version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./client:/app
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "6034:6034"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD='qwe987'
      - DB_NAME=iot
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=qwe987
      - MYSQL_DATABASE=iot
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/require.sql:/docker-entrypoint-initdb.d/require.sql
volumes:
  mysql-data:
